Document: midenok-setup
Title: Debian midenok-setup Manual
Author: <insert document author here>
Abstract: This manual describes what midenok-setup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/midenok-setup/midenok-setup.sgml.gz

Format: postscript
Files: /usr/share/doc/midenok-setup/midenok-setup.ps.gz

Format: text
Files: /usr/share/doc/midenok-setup/midenok-setup.text.gz

Format: HTML
Index: /usr/share/doc/midenok-setup/html/index.html
Files: /usr/share/doc/midenok-setup/html/*.html
