macro(pop list out)
    list(GET ${list} 0 ${out}) 
    list(REMOVE_AT ${list} 0)
endmacro()

macro(join list delim out)
    set(sep "")
    foreach(arg ${${list}})
        set(${out} "${${out}}${sep}${arg}")
        set(sep ${delim})
    endforeach()
endmacro()

macro(symlink src dst)
    get_filename_component(file "${src}" NAME)
    set(dst_file "${dst}/${file}")
    execute_process(
        COMMAND cmake -E create_symlink "${src}" "${dst_file}"
        RESULT_VARIABLE rc)
    if(rc)
        message(FATAL_ERROR "create_symlink failed! old:${src} new:${dst_file}")
    endif()
endmacro()

function(FILE CMD)
    if(CMD STREQUAL INSTALL)
        set(args ${ARGN})
        join(args " " trace)
        message(${trace})
        while (args)
            pop(args arg)
            if(arg STREQUAL DESTINATION)
                pop(args dest)
            elseif(arg STREQUAL FILES)
                # FIXME: multiple files?
                pop(args files)
            endif()
        endwhile()
        message("dest: " ${dest} "; files: " ${files})
        symlink(${files} ${dest})
    else()
        _FILE(${ARGV})
    endif()
endfunction(FILE)
