#!/bin/bash
optstring_short="bcCdDg:m:o:psS:t:TvZ:"
optstring_long="group:,mode:,owner:,preserve-timestamps,strip,strip-program:,suffix:,target-directory:,no-target-directory,verbose,preserve-context,context:,help,version,backup::"
TEMP=$(getopt -o $optstring_short --long $optstring_long -n 'install' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

mode=not_set
unset verbose
unset target
set_mode() { [ "$mode" == not_set ] && mode=$1; }

while true
do
    case "$1" in
        -d|--directory) set_mode create_dirs; shift ;;
        -D) shift ;;
        -t|--target-directory) set_mode target; target="$2"; shift 2 ;;
        -T|--no-target-directory) set_mode dest; shift ;;
        -v|--verbose) verbose=-v; shift ;;
        --help) /usr/bin/install $1; set -- --version ;;
        --version) echo "*** This spoofed install creates symlinks instead of copy! ***"; exit ;;
        -b|-c|-C|-p|-s|--preserve-timestamps|--strip|--preserve-context) shift ;;
        -g|-m|-o|-S|-Z|--group|--mode|--owner|--strip-program|--suffix|--context) shift 2 ;;
        --backup) shift; [ "$1" != "--" ] && shift ;;
        --) shift; break ;;
    esac
done

error() { echo "$0: $@"; echo "Try \`$0 --help' for more information."; exit 1; }

if [ "$mode" == not_set ]
then
    case $# in
        0) error "missing file operand" ;;
        1) error "missing destination file operand after \`$1'" ;;
    esac

    if [ $# -gt 2 -o -d "${!#}" ]
    then
        mode=dir
    else
        mode=dest
    fi
fi

dir_dest_mode()
{
    unset opt
    if [ $mode == "dest" ]
    then
        opt=-T
    fi
    dest="${!#}"
    dir=$(dirname "$dest")
    [ -n "$dir" -a '!' -d "$dir" ] && mkdir -p "$dir"
    i=1
    for f
    do
        [ -n "${f##/*}" ] && f="$(pwd)/${f}"
        ln -f -s $opt "$f" "$dest"
        i=$((i+1))
        [ $i -eq $# ] && break;
    done
}

create_dirs_mode()
{
    for d
    do
        [ -d "$d" ] || mkdir $verbose -p "$d"
    done
}

case $mode in
    dir) dir_dest_mode "$@" ;;
    dest) dir_dest_mode "$@" ;;
    target) mode=dir; dir_dest_mode "$@" "$target" ;;
    create_dirs) create_dirs_mode "$@" ;;
esac

#/usr/bin/install "$@"
