macro(pop list out)
    list(GET ${list} 0 ${out}) 
    list(REMOVE_AT ${list} 0)
endmacro()

macro(join list delim out)
    set(sep "")
    foreach(arg ${${list}})
        set(${out} "${${out}}${sep}${arg}")
        set(sep ${delim})
    endforeach()
endmacro()

function(FILE CMD)
    if(CMD STREQUAL INSTALL)
        set(args ${ARGN})
        join(args " " trace)
        message(${trace})
        while (args)
            pop(args arg)
            if(arg STREQUAL DESTINATION)
                pop(args dest)
            elseif(arg STREQUAL FILES)
                # FIXME: multiple files?
                pop(args files)
            endif()
        endwhile()
        message("dest: " ${dest} "; files: " ${files})
    else()
        _FILE(${ARGV})
    endif()
endfunction(FILE)
