#!/bin/sh
rsync -aHP \
    --delete \
    --exclude '/jail' \
    --exclude '/dev/*' \
    --exclude '/proc/*' \
    --exclude '/sys/*' \
    --exclude '/tmp/*' \
    --exclude '/run/*' \
    --exclude '/boot/*' \
    --exclude '/home/*' \
    --exclude '/opt/*' \
    --exclude '/var/tmp/*' \
    --exclude '/lib/init/rw/*' \
    --exclude '/var/lib/nfs/rpc_pipefs/*' \
    --exclude '/media/*' \
    --exclude '/mnt/*' / "$@"
