#!/usr/bin/env perl

use strict;
use warnings;

use IO::Socket::INET;
# auto-flush on socket
$| = 1;

my $continue = 1;
$SIG{INT} = sub { $continue = 0 };


while ($continue) {
    my $timestamp = localtime(time);
    my $msg = "japh - $timestamp\n";

    # Create a connecting socket
    my $socket = new IO::Socket::INET (
        PeerHost => 'localhost',
        PeerPort => '7777',
        Proto => 'tcp',
    );

    if (!$socket) {
      sleep 3;
      next;
    }

    for (my $i= 0; $i < 3; ++$i) {
      my $size = $socket->send($msg);
      print "$i: Sent ${size}!\n";

      sleep 1;
    }
    $socket->close();
}
