#!/usr/bin/env perl

use strict;
use warnings;

use IO::Socket::INET;
# auto-flush on socket
$| = 1;


# Creating a listening socket
my $socket = new IO::Socket::INET (
    LocalHost => '0.0.0.0',
    LocalPort => '7777',
    Proto => 'tcp',
    Listen => 5,
    Reuse => 1
);
die "Cannot create socket $!\n" unless $socket;

$SIG{INT} = sub { $socket->close(); exit 0; };

while(1) {
    my $socket = $socket->accept();

    # Get information about a newly connected client
    my $client_address = $socket->peerhost();

    # Read up to 1024 characters from the connected client
    $socket->blocking(0);
    while (my $data = <$socket>) {
      print "$client_address - $data\n";
    }
    last;
}
